Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.vm.hostname = "asterix"
    config.vm.network "private_network", ip: "10.0.0.100"
    config.vm.provider "virtualbox" do |vbox|
        vbox.name = "asterix"
        vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "20"]
        vbox.memory = 256
    end

    config.vm.provision "shell", inline: "hostnamectl set-hostname asterix"
end
