Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    config.vm.network "private_network", type: "dhcp"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 8443

    config.vm.provider "virtualbox" do |vbox|
        vbox.name = "asterix"
        vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "20"]
        vbox.memory = 256
    end

    config.vm.provision "shell", inline: "hostnamectl set-hostname asterix"
    config.vm.hostname = "asterix"
end
